---
name: Release Patch
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: cliffano/release-action@main
        with:
          release_type: 'patch'
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
